[package]
name = "scrumtask-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.122"
ellipse = "0.2.0"
itertools = "0.13.0"

[dev-dependencies]
tempfile = "3.11.0"
